"""
Report Generator Module
=======================
Generates Markdown and JSON reports from scan results.
"""

import json
import datetime
from typing import List, Dict, Any

def generate_markdown_report(scan_results: List[Dict[str, Any]], output_file: str = None) -> str:
    """
    Generate a professional Markdown report from scan results.

    Parameters
    ----------
    scan_results : list of dicts, each dict representing an enriched IOC.
    output_file  : optional path to write the report to.

    Returns
    -------
    The report as a string.
    """
    timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    total = len(scan_results)
    malicious = sum(1 for r in scan_results if r.get("classification") == "MALICIOUS")
    suspicious = sum(1 for r in scan_results if r.get("classification") == "SUSPICIOUS")
    clean = sum(1 for r in scan_results if r.get("classification") == "CLEAN")

    md_lines = [
        "# 🛡️ Automated Threat Intelligence & IOC Scan Report",
        f"\n**Generated At:** {timestamp}  ",
        "**Pipeline:** Automated Threat Intel & IOC Scanner v1.0.0\n",
        "---",
        "## 📊 Executive Summary",
        "| Metric | Count |",
        "| :--- | :--- |",
        f"| **Total IOCs Scanned** | {total} |",
        f"| **🔴 Malicious** | {malicious} |",
        f"| **🟡 Suspicious** | {suspicious} |",
        f"| **🟢 Clean** | {clean} |",
        "\n---",
        "## 🔍 Detailed IOC Analysis",
        "| IOC | Type | Classification | Risk Score | Details |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]

    for r in scan_results:
        ioc = r.get("ioc", "")
        t = r.get("type", "").upper()
        classification = r.get("classification", "UNKNOWN")
        score = r.get("risk_score", 0)
        details = r.get("details", "N/A")

        # Emoji badge
        badge = {
            "MALICIOUS": "🔴",
            "SUSPICIOUS": "🟡",
            "CLEAN": "🟢",
        }.get(classification, "⚪")

        md_lines.append(
            f"| `{ioc}` | {t}` | {t} | {badge} **{classification}** | **{score}/100** | {details} |"
            .replace("`ioc`", f"`{ioc}`")
        )

    md_lines.extend([
        "\n---",
        "*Report generated by Automated Threat Intel & IOCScanner Pipeline (ajit028)*",
    ])

    report_content = "\n".join(md_lines)

    if output_file:
        try:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(report_content)
            print(f"[+] Markdown report saved to {output_file}")
        except OSError as exc:
            print(f"[-] Failed to write report: {exc}", file=sys.stderr)

    return report_content

def generate_json_report(scan_results: List[Dict[str, Any]], output_file: str = None) -> Dict[str, Any]:
    """
    Generate a structured JSON report from scan results.

    Parameters
    ----------
    scan_results : list of dicts, each dict representing an enriched IOC.
    output_file  : optional path to write the JSON report to.

    Returns
    -------
    The report as a dict (also written to file if output_file provided).
    """
    report = {
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
        "total_iocs": len(scan_results),
        "results": scan_results,
    }

    if output_file:
        try:
            with open(output_file, "w", encoding="utf-8") as f:
                json.dump(report, f, indent=4, sort_keys=True)
            print(f"[+] JSON report saved to {output_file}")
        except OSError as exc:
            print(f"[-] Failed to write JSON report: {exc}", file=sys.stderr)

    return report